{
    "name": """POS: show product qty Location""",
    "summary": """Adds available quantity at products in POS""",
    "category": "Point Of Sale",
    "images": [],
    "version": "14.0.1.1.0",
    "application": False,
    "author": "VERTS Services India Pvt. Ltd.",
    "support": "VERTS Services India Pvt. Ltd.",
    "website": "https://verts.co.in/",
    "depends": ["point_of_sale", "stock"],
    "external_dependencies": {"python": [], "bin": []},
    "data": ["views/pos_common_assets.xml"],
    "qweb": ["static/src/xml/qty_available.xml"],
    "post_load": None,
    "pre_init_hook": None,
    "post_init_hook": None,
    "uninstall_hook": None,
    "auto_install": False,
    "installable": True,
}
